"""reset_migration_final_v2

Revision ID: 2422a691ee08
Revises: 3fd7ac262b8e
Create Date: 2026-05-14 00:28:46.782048

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2422a691ee08'
down_revision: Union[str, None] = '3fd7ac262b8e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
